Update gitignore. Log file names as images

diff --git a/scene_common/Makefile b/scene_common/Makefile
--- a/scene_common/Makefile
+++ b/scene_common/Makefile
@@ -12,12 +12,17 @@
 IMAGE=scenescape-common-base
 VERSION:=$(shell cat ../version.txt)
 BASE_OS_IMAGE=ubuntu:22.04
+BUILD_DIR=build
+LOG_FILE=$(BUILD_DIR)/$(IMAGE).log
+SHELL:=/bin/bash
 
 default: build-image
 
 .PHONY: build-image
 build-image: Dockerfile
-	env BUILDKIT_PROGRESS=plain \
+	@echo "------- STARTING BUILD OF IMAGE: $(IMAGE):$(VERSION) -------"
+	@mkdir -p $(BUILD_DIR)
+	@-env BUILDKIT_PROGRESS=plain \
 	  docker build $(REBUILDFLAGS) \
 	    --build-arg BASE_OS_IMAGE=$(BASE_OS_IMAGE) \
 	    --build-arg http_proxy=$(http_proxy) \
@@ -25,8 +30,16 @@ build-image: Dockerfile
 	    --build-arg no_proxy=$(no_proxy) \
 	    --build-arg CERTDOMAIN=$(CERTDOMAIN) \
 	    --build-arg USER_ID=$$UID \
-	    --rm -t $(IMAGE):$(VERSION) -f ./Dockerfile .. \
-	&& docker tag $(IMAGE):$(VERSION) $(IMAGE):latest
+	    --rm -t $(IMAGE):$(VERSION) -f ./Dockerfile .. 2>&1 | tee $(LOG_FILE); \
+	status=$${PIPESTATUS[0]}; \
+	if [ $$status -eq 0 ]; then \
+		docker tag $(IMAGE):$(VERSION) $(IMAGE):latest; \
+		echo -e "\033[0;32m------- BUILD OF IMAGE $(IMAGE):$(VERSION) COMPLETED SUCCESSFULLY -------\033[0m"; \
+		echo "Log file created at $(LOG_FILE)"; \
+	else \
+		echo -e "\033[0;31m------- BUILD OF IMAGE $(IMAGE):$(VERSION) FAILED. CHECK $(LOG_FILE) FOR DETAILS. -------\033[0m"; \
+		exit 1; \
+	fi
 
 .PHONY: rebuild
 rebuild:
