Create docker image for SceneScape (#47)
* Initial commit

* chmod +x for .sh scripts

* Add permissions

* Configure jobs

* Add license

* omit autolm scripts

* debug env variables

* Revert "debug env variables"

This reverts commit b7886ce46bbf92a5ca09ee0097d341acd0ba09d6.

* Virus scan and license check

* Add workflow

* actions/checkout@v4

* drony fix

* drony fix

* debug github event variable

* uses: fsfe/reuse-action@v5

* uses: fsfe/reuse-action@v5.0.0

* Reuse open-edge-platform/orch-ci/.github/actions/security/

* trigger workflow

* fsse reuse

* Dorny v

* fsfe

* check manual execution

* dorny

* dorny

* clamav

* workflow_dispatch

* Replace scans to a separate PR

* Adjust .md

* Dorny version fix

* Remove scand workflow

* Update .github/workflows/migration-tests.yml

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update .github/workflows/migration-tests.yml

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Revert dummy mistake

* remove autolm

* re-adjust workspace setup workflow

* set run_type env variable

* debug environment

* test workflow

* update task status

* move workspace setup to migrationtest workflow

* remove setup workflow file

* remove blak line

* Bump versions to lates

* run cron job in PST

* add pre-merge job

* Test pre-merge pipeline

* debug pre-merge

* test run_build

* fix workflow

* test build

* add versioning file

* update pre-merge pipeline

* comment build pipeline condition

* debug env variables

* debug build_type

* capture output

* refactor build check

* set env variables

* refactor build workflow

* set correct file name

* use correct branch name source

* create job for each project

* realign comment

* Migration performance tests stage into GitHub Actions (#52)

* add perf test target

* run performance tests

* comment perfomance test job

* track the changes

* update migration tracker

* fix yaml syntax

* trigger workflow

* realign comment

* comment strategy part

* Migration stability tests stage into GitHub Actions (#53)

* add stabiity tests target

* fix indentation

* update migration tracker

* supress command output

* Update Makefile

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* [CI/CD] Run Tests jobs migration (#43)

* Init

* Fixes

* Update .github/ci_migration.md

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Dummy test

* Update

* Add names

* Update

* Delete separate file

* Add tests

* test 1

* test 2

* test 3

* Newline to ./autocalibration/Makefile

* Move SUPASS to ENV

* Remove newliner

* Comment Run Stability Tests

* Use SHA for tools versions

* Move secret value

* actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update .github/scripts/set_make_env_vars.sh

Change the license

Co-authored-by: Lukasz Talarczyk <lukasz.talarczyk@intel.com>

* remove hardcoded pasword

* change license in makefile

* Add manual trigering

* add schedule triggering

---------

Co-authored-by: Yermolenko, Dmytro <dmytro.yermolenko@intel.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: Lukasz Talarczyk <lukasz.talarczyk@intel.com>

diff --git a/.github/workflows/migration-tests.yml b/.github/workflows/migration-tests.yml
--- a/.github/workflows/migration-tests.yml
+++ b/.github/workflows/migration-tests.yml
@@ -53,6 +53,9 @@ jobs:
     outputs:
       filtered_projects: ${{ steps.filter-changes.outputs.filtered_projects }}
       other_changed_projects: ${{ steps.filter-changes.outputs.other_changed_projects }}
+      build_type: ${{ steps.set-env.outputs.build_type }}
+      branch_name: ${{ steps.set-env.outputs.branch_name }}
+      change_target: ${{ steps.set-env.outputs.change_target }}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
@@ -74,15 +77,16 @@ jobs:
 
           echo "filtered_projects=$filtered_projects" >> $GITHUB_OUTPUT
           echo "other_changed_projects=$other_changed_projects" >> $GITHUB_OUTPUT
-      - name: "Setup environment"
+      - name: "Setup Environment"
+        id: set-env
         shell: bash
         env:
           RUN_TYPE: ${{ github.event.inputs.run_type || '' }}
         run: |
           .github/scripts/check_and_set-build-type.sh
-      - name: Debug environment
+          .github/scripts/set_make_env_vars.sh
+      - name: "Debug Environment"
         run: |
-          echo "✅ BUILD_TYPE: $BUILD_TYPE"
           echo "✅ JIRA_RELEASE: $JIRA_RELEASE"
           echo "✅ VERSION: $VERSION"
           echo "✅ ARTIFACTORY_PATH: $ARTIFACTORY_PATH"
@@ -104,20 +108,68 @@ jobs:
         id: setup_python
         with:
           python-version: '3.13'
-      - name: "Cache Python virtualenv"
+      - name: "Cache Python Virtualenv"
         uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         with:
           path: venv
           key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('ci/requirements.txt') }}
           restore-keys: |
             venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-
-      - name: "Set up venv and install dependencies"
+      - name: "Set Up Venv and Install Dependencies"
         run: |
           rm -rf venv
           python -m venv venv
           echo "$PWD/venv/bin" >> $GITHUB_PATH
           pip install --upgrade pip
           pip install -r .github/resources/requirements.txt
+  pre-merge-pipeline:
+    name: "Pre-merge Pipeline"
+    needs: pre-checks
+    if: ${{ needs.pre-checks.outputs.filtered_projects != '[]' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    ###
+    # The strategy is only relevant if we're using our own runner instead of Github Actions
+    # With self-hosted runner, docker images can be cached avoiding the need of rebuild them repeatedly
+    # Using Github hosted runner, we must rebuild the images whenever any component changes
+    ###
+    # strategy: # creates a job for each item in the filtered_projects output
+    #   fail-fast: false
+    #   matrix:
+    #     project_folder: ${{ fromJson(needs.pre-checks.outputs.filtered_projects) }}
+    env:
+      BUILD_TYPE: ${{ needs.pre-checks.outputs.build_type }}
+      BRANCH_NAME: ${{ needs.pre-checks.outputs.branch_name }}
+      CHANGE_TARGET: ${{ needs.pre-checks.outputs.change_target }}
+      EXTRA_BUILD_FLAGS: ''
+      SUPASS: ${{ secrets.SUPASS }}
+    steps:
+      - name: "Checkout code"
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+      - name: "Debug Env Passed to Make"
+        run: |
+          echo "BUILD_TYPE: $BUILD_TYPE"
+          echo "BRANCH_NAME: $BRANCH_NAME"
+          echo "CHANGE_TARGET: $CHANGE_TARGET"
+      - name: "Build Project"
+        run: |
+          if make build; then
+            echo "BUILD_FOR_TESTS=true" >> $GITHUB_ENV
+          else
+            echo "BUILD_FOR_TESTS=false" >> $GITHUB_ENV
+            exit 1
+          fi
+
+      - name: "Run Tests"
+        run: make run_tests
+      # the original stage was explicitely disabled in Jenkinsfile using `when { expression { false } }`
+      # - name: Run Performance Tests
+      #   run: make run_performance_tests
+      #- name: "Run Stability Tests"
+      #  if: ${{ (env.BUILD_TYPE == 'WEEKLY' || env.BUILD_TYPE == 'DAILY') && env.BUILD_FOR_TESTS == 'true' }}
+      #  run: make run_stability_tests
+
   filter:
    name: "Filter Changed Paths"
    runs-on: ubuntu-latest
